[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.25

[cursor]
style = {shape = "Underline", blinking = "Always"}
