[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Everforest-Dark-Hard
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Everforest-Dark-Hard
GtkTheme=oomox-Everforest-Dark-Hard
IconTheme=oomox-Everforest-Dark-Hard
MetacityTheme=oomox-Everforest-Dark-Hard
